// export { typeDef as Team } from './team'
// export { default as Photo } from './photo'
export { typeDef as Photo } from './photo'
// export { Query, resolvers } from './query'
export { Schema, typeDefs, resolvers } from './schema'
