export { default as Photo } from './photo'
export { default as Query } from './query'
export { default as Mutation } from './mutation'
export { typeDefs } from './typedefs'
export { queryResolvers, mutationResolvers } from './resolvers'
